version: "3.8"

services:
  # Enhanced E2E test runner with screenshot fixes
  screenshot-test:
    build:
      context: .
      dockerfile: Dockerfile.e2e-enhanced
    volumes:
      - ./tests/e2e/docker/test-results:/workspace/test-results
      - ./tests/e2e/docker/test-results/screenshots:/workspace/test-results/screenshots
      - ./tests/e2e/docker/test-results/debug-screenshots:/workspace/test-results/debug-screenshots
      - ./tests/e2e/docker/test-results/plugin-screenshots:/workspace/test-results/plugin-screenshots
    environment:
      - DISPLAY=:99
      - NODE_ENV=test
      - CI=true
      - SCREENSHOT_DEBUG=true
    tmpfs:
      - /tmp
      - /dev/shm:rw,nosuid,nodev,exec,size=2g
    shm_size: 2gb
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    command: /usr/local/bin/run-e2e-enhanced.sh

  # Standalone debug test
  debug-test:
    build:
      context: .
      dockerfile: Dockerfile.e2e-enhanced
    volumes:
      - ./tests/e2e/docker/test-results/debug-screenshots:/workspace/test-results/debug-screenshots
    environment:
      - DISPLAY=:99
      - NODE_ENV=test
      - DEBUG=true
    tmpfs:
      - /tmp
      - /dev/shm:rw,nosuid,nodev,exec,size=2g
    shm_size: 2gb
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    command: >
      bash -c "
        service dbus start &&
        Xvfb :99 -screen 0 1920x1080x24 -ac +extension GLX +render -noreset -nolisten tcp -dpi 96 &
        XVFB_PID=$$! &&
        export DISPLAY=:99 &&
        echo 'Waiting for Xvfb...' &&
        timeout=10 &&
        while [ $$timeout -gt 0 ]; do
          if xdpyinfo -display :99 >/dev/null 2>&1; then
            echo 'Xvfb ready' &&
            break
          fi
          sleep 1 &&
          timeout=$$((timeout - 1))
        done &&
        fluxbox -display :99 &
        WM_PID=$$! &&
        cd /workspace &&
        su obsidian -c 'export DISPLAY=:99 && export HOME=/home/obsidian && cd /workspace && node tests/e2e/docker/debug-display-test.js' &&
        kill $$XVFB_PID $$WM_PID 2>/dev/null || true
      "

  # Screenshot verification service
  verify-screenshots:
    image: ubuntu:22.04
    volumes:
      - ./tests/e2e/docker/test-results:/test-results
      - ./scripts:/scripts
    command: >
      bash -c "
        apt-get update && apt-get install -y bash &&
        bash /scripts/verify-screenshots.sh
      "
    depends_on:
      - screenshot-test

networks:
  default:
    driver: bridge