version: '3.8'

services:
  e2e-obsidian-tests:
    build:
      context: .
      dockerfile: Dockerfile.e2e-obsidian
    container_name: exocortex-e2e-obsidian
    environment:
      - NODE_ENV=test
      - CI=true
      - DISPLAY=:99
      - FORCE_COLOR=1
    volumes:
      # Mount source code for development (optional)
      - ./src:/app/src:ro
      - ./tests/e2e-obsidian:/app/tests/e2e-obsidian:ro
      - ./jest.e2e-obsidian.config.js:/app/jest.e2e-obsidian.config.js:ro
      # Mount results directory for test output
      - ./test-results:/app/test-results
    working_dir: /app
    command: ["/app/run-e2e-tests.sh"]
    # Add resource limits to prevent issues in CI
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    # Network configuration
    networks:
      - e2e-network

networks:
  e2e-network:
    driver: bridge