name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Create release package
        run: |
          mkdir release-files
          cp main.js manifest.json release-files/
          # Copy styles.css only if it exists
          [ -f styles.css ] && cp styles.css release-files/ || true
          cd release-files
          zip -r ../${{ github.event.repository.name }}.zip ./*

      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Extract changelog for version
        id: changelog
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          # Remove 'v' prefix if present
          VERSION_NUM=${VERSION#v}

          # Extract changelog entry for this version
          CHANGELOG=$(awk "/## \[$VERSION_NUM\]/{flag=1; next} /## \[/{flag=0} flag" CHANGELOG.md)

          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details."
          fi

          # Save to file
          echo "$CHANGELOG" > release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            main.js
            manifest.json
            ${{ github.event.repository.name }}.zip
          body_path: release_notes.md
          draft: false
          prerelease: false
